Update osrd-website/content/about/use-case/strategic-timetable.xx.md
DGEXSolutions/osrd-website pull request #100
Opened 2023-04-11 17:07 UTC by Christian-CROCHE

All these explanation seem very France-oriented to me. Couldn’t these explanations be less chauvin?

2023-04-11 17:18 UTC, axrolld requested changes
One typo but the rest of the proposals seem good to me.
I don't know how the process works in other countries so i'm not very inspired on how to make this page "less French", but feel free to send other pull requests if you want to !

Thank you again for your contribution :)

2023-04-12 10:12 UTC, multun commented
@Christian-CROCHE what do you think of https://github.com/DGEXSolutions/osrd-website/pull/80?

2023-04-12 15:38 UTC, Christian-CROCHE commented on content/about/use-case/strategic-timetable.fr.md
> +La première phase du processus de conception des plans de transport commence très en amont : 10&bnsp;ans (A-10) avant le jour de circulation. Elle a pour objectif **la proposition de plusieurs scenar
Should I modify my proposal? I’m a rooky in GitHub and not used to its features…

2023-04-12 15:43 UTC, Christian-CROCHE commented
> @Christian-CROCHE what do you think of #80? I didn't like these explanations either: they felt very dense and jargon-heavy, so I entirely rewrote the thing. Unfortunately, we somewhat forgot to integrate these changes. I would love to get your opinion on this take!

I’ll take some time to review this later. I’m currently following a training and thus, not really available.

- Should I review the two pages (English and French) like I did for the other pages?
- Are we supposed to write everything in English as we are mostly French, in order for all the other contributors to understand what we are saying?

2023-04-12 16:31 UTC, multun commented
> I understand right now that the pull request#80 is already a modification proposal that you just « published », is that right?

That's it! All changes start as proposals, which can be reviewed, and integrated once all participants agree

> How should I propose you modifications on this?

There are a couple of ways we could do it:
 - We could also hop on a call and chat about it (You should have received a private message on your SNCF teams account)
 - Github has an integrated [review feature](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request). That's what we usually use, but it requires a little bit of getting used to.

> Are we supposed to write everything in English as we are mostly French, in order for all the other contributors to understand what we are saying?

That's the general idea, but not a hard rule either:
 - we try to communicate in english, as if a visible enough portion of the project were only available in french, it would make it unwelcoming to non-french contributors (which, believe it or not, are so far as interested as french contributors)
 - we don't want anyone to feel excluded either: if someone makes any kind of contribution in a language other than English, we'll handle it as usual

2023-04-12 16:39 UTC, axrolld commented on content/about/use-case/strategic-timetable.fr.md
> +La première phase du processus de conception des plans de transport commence très en amont : 10&bnsp;ans (A-10) avant le jour de circulation. Elle a pour objectif **la proposition de plusieurs scenar
Ideally yes, but we can also fix it. Are you using the Github interface to modify the files ?

2023-04-18 10:39 UTC, Christian-CROCHE commented on content/about/use-case/strategic-timetable.fr.md
> +La première phase du processus de conception des plans de transport commence très en amont : 10&bnsp;ans (A-10) avant le jour de circulation. Elle a pour objectif **la proposition de plusieurs scenar
```suggestion
La première phase du processus de conception des plans de transport commence très en amont : 10&bnsp;ans (A-10) avant le jour de circulation. Elle a pour objectif **la proposition de plusieurs scenarios de circulation** sur des infrastructures ferroviaires existantes ou prospectives. Durant cette phase, SNCF Réseau (gestionnaire de l’infrastructure ferroviaire française et responsable de l’affectation et de la vente des sillons) collectionne les demandes des **AO** (autorités organisatrices) et des **EF** (entreprises ferroviaires) en termes de mobilité. Les demandes sont transmises sous la forme de **schémas de dessertes** : représentation des trains demandés, leur itinéraire et les arrêts à desservir.
```

2023-04-27 20:02 UTC, closed without merging