docs: entirely translate "Contribute to OSRD"
DGEXSolutions/osrd-website pull request #78
Opened 2023-02-01 13:55 UTC by celine-sncf

2023-02-01 15:14 UTC, multun requested changes

2023-02-01 15:14 UTC, multun commented on content/docs/guides/contribute/_index.en.md
> +Before making any change, learn about what's already there :
```suggestion
Just like with any project, changes rely on past work.
Before making changes, it is best to learn about what's already there:
```

2023-02-01 15:14 UTC, multun commented on content/docs/guides/contribute/_index.en.md
> +- You can contact the last developers who have worked on code areas that are of interest to you
```suggestion
- [read technical documentation]({{< ref "/docs" >}})
- read the existing source code related to your project
- chat with developers who last worked on areas you are interested in
```

2023-02-01 17:48 UTC, axrolld approved these changes

2023-02-03 13:42 UTC, multun approved these changes

2023-02-03 13:42 UTC, merged