docs: reference: update architecture diagrams
DGEXSolutions/osrd-website pull request #85
Opened 2023-02-10 10:27 UTC by flomonster

2023-03-17 09:56 UTC, younesschrifi approved these changes

2023-04-11 14:50 UTC, Khoyo requested changes

2023-04-11 17:39 UTC, axrolld commented on content/docs/reference/architecture.fr.svg
Could we actually write `infrastructure` instead of `infra`?

2023-04-11 17:40 UTC, axrolld commented on content/docs/reference/architecture.en.svg
I'd prefer `Operational studies` rather than `Exploitation studies` in front.

2023-04-12 10:29 UTC, axrolld requested changes

2023-04-12 10:29 UTC, axrolld commented on content/docs/reference/architecture.en.svg
Sorry i didn't write it down here as well but there are some `infra `that should be replaced by `infrastructure` here as well in my opinion

2023-04-18 15:06 UTC, axrolld approved these changes
🚀

2023-04-18 15:16 UTC, merged