contribute: Add and update french translations
DGEXSolutions/osrd-website pull request #94
Opened 2023-03-27 13:34 UTC by bloussou

follow up of #92

2023-03-27 13:42 UTC, flomonster approved these changes
LGTM. Thanks :+1:

2023-03-27 15:07 UTC, axrolld requested changes

2023-03-27 15:07 UTC, axrolld commented on content/docs/guides/contribute/bug-reports.fr.md
> +  - une ou plusieurs `area:<affected_area>` si possible, si la zone affectée n'est pas connue, laissez-la vide, elle sera ajoutée plus tard par un autre membre de l'équipe.
```suggestion
  - une ou plusieurs `area:<affected_area>` si possible (si la zone affectée n'est pas connue, laissez-la vide et elle sera ajoutée plus tard par un autre membre de l'équipe).
```
Un peu trop de virgules dans cette ligne

2023-03-27 15:07 UTC, axrolld commented on content/docs/guides/contribute/code.fr.md
>     - Il est nécessaire d'obtenir l'approbation de [quelqu'un familier avec le code](https://github.com/DGEXSolutions/osrd/blob/dev/.github/CODEOWNERS) pour pouvoir intégrer le changement
```suggestion
   - Il est nécessaire d'obtenir l'approbation d'un [code owner](https://github.com/DGEXSolutions/osrd/blob/dev/.github/CODEOWNERS) pour pouvoir intégrer le changement
```
Ca aurait du sens d'écrire ça comme ça ?

2023-03-28 10:17 UTC, axrolld approved these changes
🐎

2023-03-29 07:54 UTC, merged