Update osrd-website/content/about/use-case/_index.xx.md
DGEXSolutions/osrd-website pull request #99
Opened 2023-04-11 16:56 UTC by Christian-CROCHE

I guess the included network will not only be the French one but also the infrastructure of the different contributors, no? I propose here only the necessary modification for the French version (my language), but it applies to the English one too.

2023-04-11 17:56 UTC, axrolld requested changes

2023-04-11 17:56 UTC, axrolld commented on content/about/use-case/_index.fr.md
> +Notre mission est de fournir un outil de simulation qui peut être utilisé dans **toutes les étapes de la phase de conception** (planification des horaires et études d’exploitation), sur une **échelle
```suggestion
Notre mission est de fournir un outil de simulation qui peut être utilisé dans **toutes les étapes de la phase de conception** (planification des horaires et études d’exploitation), sur une **échelle géographique nationale** (comprenant _a minima_ le réseau français mais pouvant s'étendre aux réseaux modélisés par des contributeurs) et avec une **granulométrie variable des détails**. De plus, dans la phase opérationnelle, le projet OSRD propose un service pour tracer des **sillons de dernières minutes** (tranche d’espace-temps durant laquelle l’infrastructure est affectée à la circulation d’un train spécifique) dans la capacité résiduelle théorique ou réelle du réseau ferroviaire, une fois que les autres circulations ont été déjà planifiées.
```
Our mission sticks to the French network, even though OSRD can be used for other networks of course

2023-04-13 17:36 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +Notre mission est de fournir un outil de simulation qui peut être utilisé dans **toutes les étapes de la phase de conception** (planification des horaires et études d’exploitation), sur une **échelle
New suggestion OK for for me.

2023-04-13 17:40 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
This first proposal can be abandonned. The further suggestion by @axrolld has been accepted. Should I "Delete the file"?

2023-04-17 15:39 UTC, axrolld requested changes

2023-04-18 08:52 UTC, axrolld approved these changes

2023-04-27 20:02 UTC, closed without merging